"use strict";
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const expected = "10551db1e054acda5e66b7e89bf96ab7999c6ea0f68135d4b72cec6541c753bc";
const root = path.join(__dirname, "..", "engine", "r1.7");
const engine = path.join(root, "private-identity-transfer.js");
const actual = crypto.createHash("sha256").update(fs.readFileSync(engine)).digest("hex");
if (actual !== expected) throw new Error(`Engine r1.7 SHA mismatch: ${actual}`);
if (fs.existsSync(path.join(root, "runs"))) throw new Error("Forbidden engine runs directory is present.");
const forbidden = fs.readdirSync(root, { recursive: true }).filter((name) => /private-state-.*\.json(?:\.sha256)?$/i.test(String(name)));
if (forbidden.length) throw new Error(`Forbidden migration bundle(s): ${forbidden.join(", ")}`);
console.log(`ENGINE_R17_SHA_PASS ${actual}`);
