"use strict";
const { contextBridge, ipcRenderer } = require("electron");
contextBridge.exposeInMainWorld("eveTransfer", {
  getState: () => ipcRenderer.invoke("get-state"),
  chooseFolder: () => ipcRenderer.invoke("choose-folder"),
  chooseNode: () => ipcRenderer.invoke("choose-node"),
  setNode: (nodePath) => ipcRenderer.invoke("set-node", nodePath),
  setRoots: (roots) => ipcRenderer.invoke("set-roots", roots),
  analyze: () => ipcRenderer.invoke("analyze"),
  prepareTarget: (options) => ipcRenderer.invoke("prepare-target", options),
  undoPrepare: (options) => ipcRenderer.invoke("undo-prepare", options),
  verifyTarget: (options) => ipcRenderer.invoke("verify-target", options),
  review: () => ipcRenderer.invoke("review"),
  transfer: (options) => ipcRenderer.invoke("transfer", options),
  exportReport: () => ipcRenderer.invoke("export-report"),
  createSupportReport: () => ipcRenderer.invoke("create-support-report"),
  copySanitizedSummary: () => ipcRenderer.invoke("copy-sanitized-summary"),
  getHistory: () => ipcRenderer.invoke("get-history"),
  clearHistory: () => ipcRenderer.invoke("clear-history"),
  checkForUpdates: () => ipcRenderer.invoke("check-for-updates"),
  openLatestRelease: () => ipcRenderer.invoke("open-latest-release"),
  openLog: () => ipcRenderer.invoke("open-log"),
  openBackup: () => ipcRenderer.invoke("open-backup"),
  deleteCompletedBackup: () => ipcRenderer.invoke("delete-completed-backup"),
  cleanCompletedBackups: () => ipcRenderer.invoke("clean-completed-backups"),
  openTarget: () => ipcRenderer.invoke("open-target"),
  runSetup: () => ipcRenderer.invoke("run-setup"),
  copyText: (text) => ipcRenderer.invoke("copy-text", text),
  onState: (handler) => ipcRenderer.on("state", (_event, state) => handler(state)),
});
